# .github/workflows/deploy-web.yml
# This workflow builds and deploys the Expo web app to GitHub Pages.

name: Deploy Web App to GitHub Pages

on:
  push:
    branches:
      - master # Or main - the branch you push your code from

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest # Use a standard Ubuntu runner

    # Grant permissions for the GITHUB_TOKEN for this job
    permissions:
      contents: read # Allow reading repository content
      pages: write     # Allow writing to GitHub Pages
      id-token: write  # Allow writing ID tokens (required by deploy-pages@v4)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Checkout your repository code

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Use Node.js version 20 (recommended LTS)
          cache: npm # Cache npm dependencies

      - name: Install dependencies
        run: npm install # Install your project dependencies

      - name: Build web app
        # This command builds the web app and places the output in the 'dist' folder.
        # The 'publicPath' in app.json is used here to generate correct asset paths in index.html.
        run: npx expo export --platform web

      - name: Upload artifact
        # This action uploads the contents of the specified path ('./dist')
        # as a deployment artifact named 'github-pages' by default.
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist # Upload the 'dist' folder contents

      - name: Deploy to GitHub Pages
        # This action deploys the 'github-pages' artifact to GitHub Pages.
        # It should automatically handle deploying to the correct location for project sites.
        id: deployment
        uses: actions/deploy-pages@v4
